ttt15

diff --git a/.github/workflows/work1.yml b/.github/workflows/work1.yml
--- a/.github/workflows/work1.yml
+++ b/.github/workflows/work1.yml
@@ -31,7 +31,7 @@ jobs:
       - name: Sleep
         run: |
           echo sleeping...
-          sleep 30
+          sleep 20
       
       - name: Checkout2
         uses: actions/checkout@v3
@@ -60,7 +60,11 @@ jobs:
           if [ $sha = $GITHUB_SHA ]; then
             equalhead="true"
           fi
+
+          echo "equalhead: $equalhead"
           echo "equalhead=$equalhead" >> "$GITHUB_OUTPUT"
+          echo "error exit code"
+          exit 1
 
       - name: Equal head
         if: steps.headhash2.outputs.equalhead == 'true'
